service: patient-api

frameworkVersion: "2.52.1"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Scan"
          Resource:
            - { "Fn::GetAtt": ["PatientEntity", "Arn"] }
  httpApi:
    authorizers:
      serviceAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl:
          Fn::Join:
            - ""
            - - "https://cognito-idp."
              - "us-east-1"
              - ".amazonaws.com/"
              - Ref: PatientApiUserPool
        audience:
          - Ref: PatientApiUserPoolClient
functions:
  addPatient:
    handler: src/add-handler.addPatient
    events:
      - httpApi:
          path: /patient
          method: post
          authorizer: serviceAuthorizer
  getPatient:
    handler: src/get-handler.getPatient
    events:
      - httpApi:
          path: /patient/{id}
          method: get
  updatePatient:
    handler: src/update-handler.updatePatient
    events:
      - httpApi:
          path: /patient/{id}
          method: put
          authorizer: serviceAuthorizer
  deletePatient:
    handler: src/delete-handler.deletePatient
    events:
      - httpApi:
          path: /patient/{id}
          method: delete
          authorizer: serviceAuthorizer
  listPatients:
    handler: src/list-handler.listPatients
    events:
      - httpApi:
          path: /patients
          method: get
plugins:
  - serverless-plugin-typescript

resources:
  Resources:
    HttpApi:
      DependsOn: PatientApiUserPool
    PatientApiUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: patient-api-user-pool
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
    PatientApiUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: patient-api-user-pool
        AllowedOAuthFlows:
          - implicit
        AllowedOAuthFlowsUserPoolClient: true
        AllowedOAuthScopes:
          - phone
          - email
          - openid
          - profile
          - aws.cognito.signin.user.admin
        UserPoolId:
          Ref: PatientApiUserPool
        CallbackURLs:
          - https://localhost:3000
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        GenerateSecret: false
        SupportedIdentityProviders:
          - COGNITO
    serviceUserPoolDomain:
      Type: AWS::Cognito::UserPoolDomain
      Properties:
        UserPoolId:
          Ref: PatientApiUserPool
        Domain: patient-api-user-pool
    PatientEntity:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PatientEntity
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: PatientId
            AttributeType: S
        KeySchema:
          - AttributeName: PatientId
            KeyType: HASH
